name: Formatting Check

on:
  push:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up environment
        #run: bash scripts/ci/ubuntu/0-setup.sh  # This runs only in CI on Ubuntu
        run: bash scripts/ci/macos/0-setup.sh

      - name: Run format check script
        run: scripts/check_format.sh
