name: Formatting Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run format check script
        run: scripts/check_format.sh
